# Generated by Django 2.2.6 on 2019-10-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_address',
            new_name='shipping_address',
        ),
    ]
