# Generated by Django 2.2.6 on 2019-10-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20191018_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='save_address',
            field=models.BooleanField(default=False),
        ),
    ]
