# Generated by Django 2.2.6 on 2019-10-20 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_promotioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='percentage_discount',
            field=models.FloatField(default='0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
